const API = {
    OSSUrl: 'http://47.99.200.198/service/aliyun-oss/getSign',
    Login: '/user/login',
    Logout: '/user/logout',
    Welcome: '/welcome',
    EditPageList: '/edit/pageList',
    EditInsertData: '/edit/insert',
    EditUpdateData:'/edit/update',
    EditDeleteData:'/edit/delete',
    AdminUserPageList:'/user/pageList',
    AdminUserInsert:'/user/insert',
    AdminUserUpdate:'/user/update',
    AdminUserDelete:'/user/delete',
    WithdrawPageList: '/withdraw/pageList',
    WithdrawConfirm: '/withdraw/confirm',
    WithdrawClose: '/withdraw/close',
    WithdrawImport: '/withdraw/import',
    ScenicLevelInsert: '/sceniclevel/insert',
    ScenicLevelUpdate: '/sceniclevel/update',
    ScenicLevelDelete: '/sceniclevel/delete',
    ScenicLevelPageList: '/sceniclevel/pageList',
    ScenicSpotInsert: '/scenicspot/insert',
    ScenicSpotUpdate: '/scenicspot/update',
    ScenicSpotDelete: '/scenicspot/delete',
    ScenicSpotPageList: '/scenicspot/pageList',
}

export default API